// solidjs/src/App.tsx
import { createSignal } from "solid-js";

export default function App() {
  const [count, setCount] = createSignal(0);

  return (
    <main class="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-gray-950 gap-4">
      <h1 class="text-4xl font-bold text-gray-900 dark:text-white">SolidJS Boilerplate</h1>
      <p class="text-gray-500 dark:text-gray-400 text-sm">Fine-grained reactivity · No virtual DOM</p>
      <button
        class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        onClick={() => setCount(count() + 1)}
      >
        count is {count()}
      </button>
      <p class="text-sm text-gray-400">
        Edit <code class="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded">src/App.tsx</code>
      </p>
    </main>
  );
}

// vite-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
const count = ref(0);
</script>

<template>
  <main class="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-gray-950">
    <h1 class="text-4xl font-bold text-gray-900 dark:text-white">Vite + Vue 3</h1>
    <button
      class="mt-6 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
      @click="count++"
    >
      count is {{ count }}
    </button>
    <p class="mt-4 text-sm text-gray-400">
      Edit <code class="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded">src/App.vue</code>
    </p>
  </main>
</template>
