// vite-svelte/src/App.svelte
<script lang="ts">
  let count = $state(0);
</script>

<main class="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-gray-950 gap-4">
  <h1 class="text-4xl font-bold text-gray-900 dark:text-white">Vite + Svelte</h1>
  <button
    class="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors"
    onclick={() => count++}
  >
    count is {count}
  </button>
  <p class="text-gray-500 dark:text-gray-400 text-sm">
    Edit <code class="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded">src/App.svelte</code> to get started.
  </p>
</main>

// vite-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
const count = ref(0);
</script>

<template>
  <main class="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-gray-950">
    <h1 class="text-4xl font-bold text-gray-900 dark:text-white">Vite + Vue 3</h1>
    <button
      class="mt-6 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
      @click="count++"
    >
      count is {{ count }}
    </button>
    <p class="mt-4 text-sm text-gray-400">
      Edit <code class="font-mono bg-gray-100 dark:bg-gray-800 px-1 rounded">src/App.vue</code>
    </p>
  </main>
</template>
